// 389. Find the Difference

// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.


// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

// MY Solution 
public class LeetCodeProblemNo389{
    public static void main(String[] args){

        String A = "hello";
        String B = "ellohf";
        int A_len = A.length();
        int[] array = new int[26];
        int[] array2 = new int[26];
        char ans = ' ';

        for(int i = 0 ; i < A_len ; i++){
            array[A.charAt(i)-'a']++;
        }
        for(int i = 0 ; i < A_len+1 ; i++){
            array2[B.charAt(i)-'a']++;
        }
        for(int i = 0 ; i < 26 ; i++){
            if(array[i] == array2[i]){
                array[i] = 0;
                array2[i] = 0;
            }
            else{
                int asciivalue = i + 97;
                char character = (char) asciivalue;
                ans = character;
            }
        }
        System.out.println(ans);
    }
}


// LeetCode compatible code :-

class Solution {
    public char findTheDifference(String s, String t) {
        
        int s_len = s.length();
        int[] array = new int[26];
        int[] array2 = new int[26];
        char ans = s.charAt(0);

        for(int i = 0 ; i < s_len ; i++){
            array[s.charAt(i)-'a']++;
        }
        for(int i = 0 ; i < s_len+1 ; i++){
            array2[t.charAt(i)-'a']++;
        }
        for(int i = 0 ; i < 26 ; i++){
            if(array[i] == array2[i]){
                array[i] = 0;
                array2[i] = 0;
            }
            else{
                int asciivalue = i + 97;
                char character = (char) asciivalue;
                ans = character;
            }
        }
        return ans;
    }
}